version: "3"
services:

    mongodb:
        image: mongo:latest
        environment:
        - MONGO_DATA_DIR=/data/db
        - MONGO_LOG_DIR=/dev/null
        volumes:
        - ./data/db:/data/db
        ports:
        - 27017:27017
        command: mongod --smallfiles --logpath=/dev/null --quiet

    api:
        build:
            context: ./
            dockerfile: Dockerfiles/dev
        links:
        - mongodb
        depends_on:
        - mongodb
        environment:
            MONGO_URL: "mongo:27017/zbb"
        ports:
        - 8080:8080

volumes:
    db-data:
